---
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install docker
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['docker.io']

- name: Install Docker Module for Python
  pip:
    name: docker
