---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - sentry_dsn

- name: Set sentry DSN env var
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: "SENTRY_DSN={{ sentry_dsn }}"
    create: true
    mode: 0777

- name: Download sentry cli installer
  get_url:
    url: https://sentry.io/get-cli/
    dest: /tmp/sentry-cli-installer

- name: Execute the sentry cli installer
  command: /tmp/sentry-cli-installer
  changed_when: false

- name: Remove the sentry cli installer
  file:
    path: /tmp/sentry-cli-installer
    state: absent
