---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - aws_access_key_id is defined
      - aws_secret_access_key is defined

- name: Create the backup directory
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory
    owner: root
    group: root

- name: Provide aws credentials to the docker daemon
  template:
    src: ../templates/aws-credentials.j2
    dest: "/etc/systemd/system/docker.service.d/aws-credentials.conf"
    owner: root
    group: root
    mode: '600'

- name: Restart and reload docker service
  systemd:
    state: restarted
    daemon_reload: true
    name: docker
