---
- name: Download agent package
  get_url:
    url: "https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
    dest: "/tmp/amazon-cloudwatch-agent.deb"

- name: Install agent package
  ansible.builtin.apt:
    deb: "/tmp/amazon-cloudwatch-agent.deb"

- name: Copy cloudwatch config
  template:
    src: cloudwatch-config.j2
    dest: "/opt/aws/amazon-cloudwatch-agent/etc/common-config.toml"
    owner: root
    group: root
    mode: '600'

- name: Copy cloudwatch agent config
  template:
    src: cloudwatch-agent-config.j2
    dest: "/opt/aws/amazon-cloudwatch-agent/bin/config.json"
    owner: root
    group: root
    mode: '600'

- name: Start the agent
  ansible.builtin.command: |
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
    -a fetch-config -m onPremise -s
    -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json
  changed_when: false  # Can run multiple times
